### ISSUE TITLE
点击导航栏所有按钮都没有效果

### ISSUE THREAD

**Issue by L-Jovi** [lisong/code-push-web#2]
1. 搭建了 web 的服务  3001 端口进入可以看到主页  但是导航栏所有按钮点击都没有效果
  发现 code push server 点击登录按钮才能跳转到对应 web 页面上  应该是前端的问题

2. 然后在注册的时候  发现填完邮箱  下一步无法点击 。。

**Comment by lisong** [comment]
浏览器控制台有错误输出没？

**Comment by L-Jovi** [comment]
@lisong  感谢你的回复

看了下浏览器的控制台  错误输出看起来是跨域的问题  。。
![image](https://cloud.githubusercontent.com/assets/7262199/23686320/d81092aa-03e3-11e7-8410-e6b073325601.png)

😓 。。 要临时改改服务端代码嘛 。。

**Comment by lisong** [comment]
可以参考 https://github.com/lisong/code-push-web/issues/1

**Comment by L-Jovi** [comment]
感谢!

**Comment by L-Jovi** [comment]
@lisong  感谢提示  跨域问题已经找到办法解决了  到了邮件这里发不出去  看到配置中依赖了 nodemailer 的模块  host user pass 这里是需要改为自己的邮件服务器嘛

再次感谢

**Comment by lisong** [comment]
改成自己的邮箱，然后邮箱需要开启stmp设置
