### ISSUE TITLE
项目运行后出错

### ISSUE THREAD

**Issue by mirinzhang** [lisong/code-push-web#6]
build成功了，但是打开`http://localhost:3000`后页面报错；

环境：
> node@8.9.1
> npm@5.5.1
> macOS High Sierra@10.13.1

![image](https://user-images.githubusercontent.com/12370585/33199276-8d8335ac-d12a-11e7-8d5a-0c1bd96c7b8a.png)

**能帮忙看下吗，谢谢**

**Comment by iRockyZhou** [comment]
+1

**Comment by lijianfeigeek** [comment]
TypeError: Cannot read property 'length' of null
